/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package card;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author Phi Ngo
 */
public class Round2 extends javax.swing.JFrame {
    
    private static boolean Called = false;
    private List<Integer> _ListIndexGot = new ArrayList<>();

    /**
     * Creates new form Round2
     */
    public Round2() {
        initComponents();
        jButton2.setVisible(false);
        jButton3.setVisible(false);
    
    }
    
    public void OnlyCallOneTime(){
        if (Called == false){
            _ListIndexGot.addAll(DataManager.Instance().GetListIndexGot());
            _LoadNextSentence();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtPhase_Round2 = new javax.swing.JTextField();
        jRad1_round2 = new javax.swing.JRadioButton();
        jRad2_round2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jBar = new javax.swing.JProgressBar();
        jProgressLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRad1_round2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRad1_round2ActionPerformed(evt);
            }
        });

        jRad2_round2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRad2_round2ActionPerformed(evt);
            }
        });

        jButton1.setText("Trả lời");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Câu tiếp theo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Kết quả");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Vòng nâng cao");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jButton2)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jRad1_round2)
                                                        .addGap(212, 212, 212)
                                                        .addComponent(jRad2_round2)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3))
                                    .addComponent(txtPhase_Round2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)))
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressLabel)
                            .addComponent(jBar, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtPhase_Round2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRad2_round2)
                            .addComponent(jRad1_round2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public int count = 0;
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        _LoadNextSentence();
        jRad1_round2.setSelected(false);
        jRad2_round2.setSelected(false);
        jButton1.setEnabled(true);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public int countFull = 0;
    
    //Kết quả 
    static int z = 0;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        if (jRad1_round2.isSelected()){
            String Answer =  jRad1_round2.getText();
            if (DataManager.Instance().GetSentenceByPronounce(Answer).equals(txtPhase_Round2.getText())){
                JOptionPane.showMessageDialog(null, "Bạn đã trả lời đúng!!!");
                z+=1;
                int progress = 0;
                progress = DataManager.Instance().getScore();
                progress+=10;
                DataManager.Instance().setScore(progress);
                this.UpdateScore();
                
            }else{
                JOptionPane.showMessageDialog(null, "Bạn đã trả lời sai!!!");
            }
        }
        else if (jRad2_round2.isSelected()){
            String Answer =  jRad2_round2.getText();
            if (DataManager.Instance().GetSentenceByPronounce(Answer).equals(txtPhase_Round2.getText())){
                JOptionPane.showMessageDialog(null, "Bạn đã trả lời đúng!!!");
                z+=1;
                int progress = 0;
                progress = DataManager.Instance().getScore();
                progress+=10;
                DataManager.Instance().setScore(progress);
                this.UpdateScore();
            }else{
                JOptionPane.showMessageDialog(null, "Bạn đã trả lời sai!!!");
            }
        }
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Kết quả " + z + "/10");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRad1_round2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRad1_round2ActionPerformed
        // TODO add your handling code here:
        jRad2_round2.setSelected(false);
    }//GEN-LAST:event_jRad1_round2ActionPerformed

    private void jRad2_round2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRad2_round2ActionPerformed
        // TODO add your handling code here:
        jRad1_round2.setSelected(false);
    }//GEN-LAST:event_jRad2_round2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Round3 round3 = new Round3();
        round3.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void _LoadNextSentence(){
        Random Rand = new Random();
        int[] Appear = new int[2];
        int Temp = Math.abs(Rand.nextInt())%2;
        int IndexAnother = Math.abs((Rand.nextInt())%DataManager.Instance().GetSize());
        if (Temp == 0){
            Appear[0]= _ListIndexGot.get(count);
            while(IndexAnother == Appear[0]){
                IndexAnother = Math.abs((Rand.nextInt())%DataManager.Instance().GetSize());
            }
            Appear[1] = IndexAnother;
        }else{
            Appear[1]= _ListIndexGot.get(count); 
            while(IndexAnother == Appear[1]){
                IndexAnother = Math.abs((Rand.nextInt())%DataManager.Instance().GetSize());
            }
            Appear[0] = IndexAnother;
        }
        String Pronounce = DataManager.Instance().GetPronounceByIndexRound2(_ListIndexGot.get(count));
        jRad1_round2.setText(DataManager.Instance().GetPronounceByIndexRound2(Appear[0]));
        jRad2_round2.setText(DataManager.Instance().GetPronounceByIndexRound2(Appear[1]));
        jTextField1.setText(DataManager.Instance().GetWordByPronounce(Pronounce));
        txtPhase_Round2.setText(DataManager.Instance().GetSentenceByPronounce(Pronounce));
        count++;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Round2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Round2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Round2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Round2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Round2().setVisible(true);
                
            }
        });
    }
    public void UpdateScore(){
        /*Progress Bar*/
        jProgressLabel.setText("Your progress: " + DataManager.Instance().getScore() + "%");
        jBar.setValue(DataManager.Instance().getScore());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JProgressBar jBar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jProgressLabel;
    private javax.swing.JRadioButton jRad1_round2;
    private javax.swing.JRadioButton jRad2_round2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtPhase_Round2;
    // End of variables declaration//GEN-END:variables
}
